services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka_broker
    ports:
      - "29092:29092"  # для хоста (Offset Explorer / IDE)
    environment:
      # KRaft single-node
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Set time retention to 30 days hour (720 hours)
      KAFKA_LOG_RETENTION_HOURS: 720
      # max partition size
      KAFKA_LOG_RETENTION_BYTES: 1073741824 # 1 GB

      # два входа: для docker-сети и для хоста
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # single-node defaults
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  postgres-processing:
    image: postgres:16
    container_name: postgres-processing
    environment:
      POSTGRES_DB: processing
      POSTGRES_USER: app_1
      POSTGRES_PASSWORD: app_1
    ports:
      - "15432:5432"   # чтобы с хоста смотреть БД (опционально)
    volumes:
      - pgdata1:/var/lib/postgresql/data

  postgres-finished:
    image: postgres:16
    container_name: postgres-finished
    environment:
      POSTGRES_DB: finished
      POSTGRES_USER: app_2
      POSTGRES_PASSWORD: app_2
    ports:
      - "25432:5432"   # чтобы с хоста смотреть БД (опционально)
    volumes:
      - pgdata2:/var/lib/postgresql/data

  producer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_MODULE: producer-service
    image: user-message-producer:latest
    container_name: producer
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      # если у тебя в producer есть профили — оставь, если нет — можно убрать
      SPRING_PROFILES_ACTIVE: producer

  consumer-processing:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_MODULE: consumer-user-messages-1
    image: user-message-consumer:latest
    container_name: consumer-processing
    depends_on:
      - kafka
      - postgres-processing
    environment:
      SPRING_PROFILES_ACTIVE: processing
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: user-message-consumer-processing

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-processing:5432/processing
      SPRING_DATASOURCE_USERNAME: app_1
      SPRING_DATASOURCE_PASSWORD: app_1

      # чтобы таблицы создавались сами (если ты используешь JPA ddl-auto)
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  consumer-finished:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_MODULE: consumer-user-messages-1
    image: user-message-consumer:latest
    container_name: consumer-finished
    depends_on:
      - kafka
      - postgres-finished
    environment:
      SPRING_PROFILES_ACTIVE: finished
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: user-message-consumer-finished

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-finished:5432/finished
      SPRING_DATASOURCE_USERNAME: app_2
      SPRING_DATASOURCE_PASSWORD: app_2

      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pgdata1:
  pgdata2:
