spring:
  application:
    name: consumer-user-messages-finished
  kafka:
    consumer:
      group-id: user-message-consumer-finished

  datasource:
    url: jdbc:postgresql://localhost:25432/finished
    username: app_2
    password: app_2
    driver-class-name: org.postgresql.Driver

app:
  status-filter: FINISHED