spring:
  application:
    name: consumer-user-messages-processing
  kafka:
    consumer:
      group-id: user-message-consumer-processing

  datasource:
    url: jdbc:postgresql://localhost:15432/processing
    username: app_1
    password: app_1
    driver-class-name: org.postgresql.Driver

app:
  status-filter: PROCESSING